AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple CFT to create an EC2 instance with a basic web server'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06b21ccaeff8cd686  
      KeyName: myweka
      SecurityGroupIds: 
        - sg-0eb4294f799c94f0d
      SubnetId: subnet-087eec9a909b35c7a
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello from my EC2 instance!</h1>" > /var/www/html/index.html

Outputs:
  InstanceId:
    Description: The Instance ID of the created EC2 instance
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicDnsName
